import { Box, Text } from "@chakra-ui/react";
import styled from "@emotion/styled";

export const News = () => {
  return (
    <Box>
      <Text>
        NEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS NEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWSNEWS
        NEWSNEWSNEWSNEWSNEWS
      </Text>
    </Box>
  );
};
